# Generated by Django 2.2 on 2020-02-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('detail_place', models.CharField(max_length=90)),
                ('detail_trip', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time_start', models.TimeField(auto_now_add=True)),
                ('image_trip', models.ImageField(upload_to='')),
            ],
        ),
    ]
