# Generated by Django 2.2 on 2020-02-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20200223_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='detail_place',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='detail_trip',
            field=models.TextField(),
        ),
    ]
