# Generated by Django 2.2 on 2020-04-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20200426_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='booking_status',
            field=models.BooleanField(default=True),
        ),
    ]
