# Generated by Django 2.2 on 2020-04-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_trip_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='detail_place',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='detail_trip',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image_trip',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trip',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='place',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_trip',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='type_price',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
