# Generated by Django 2.2 on 2020-04-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20200429_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='image_pay',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='guide',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='nationalID',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='password',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='telephone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
